version: '3.8'
services:
  appseed-app:
    container_name: appseed_app
    build: .
    volumes:
      - ./slep:/app
    networks:
      - db_network
    command: sh -c "python manage.py makemigrations && 
              python manage.py migrate && 
              python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - API_KEY=specup-slep
    extra_hosts:
      - "host.docker.internal:host-gateway"

    depends_on:
      - redis
  redis:
    image: redis
    container_name: redis-service-slep
    ports:
      - "6379:6379"
    networks:
      - db_network

  nginx:
    container_name: nginx
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
  depends_on: 
      - appseed-app

networks:
  db_network:
    driver: bridge
 
volumes:
  slep-db-data: