# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zgz0Up2mTtoU_-CCeRPAr3tl6ubZaf0v
"""

from keras.models import load_model, save_model
import numpy as np

model = load_model('논문test.h5')

def run(sequence):
    from keras.models import load_model, save_model
    import numpy as np
     if len(sequence) == 30:
            res = model.predict(np.expand_dims(sequence, axis=0))[0]
            print(actions[np.argmax(res)])