# -*- coding: utf-8 -*-
"""sleprun

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zgz0Up2mTtoU_-CCeRPAr3tl6ubZaf0v
"""
#tensorflow = 2.10.0, numpy = 1.21.6 사용했습니다.
from keras.models import load_model, save_model
import numpy as np

model = load_model('논문test.h5')# 

def run(sequence): # 배열 [30,126] 1차원에 30개의 요소가 있고 각 요소는 126개의 요소가 있어야해요!
    if len(sequence) == 30:
            res = model.predict(np.expand_dims(sequence, axis=0))[0]
    return actions[np.argmax(res)],max(res)
 # 모델이 예측한 결과를 내뿜는데 np.argmax(res)는 가장 유사한 얘의 인덱스 즉 모델이 6개짜리면 6개중에 가장 유사한 수어의 인덱스를 리턴해줍니다
 # max(res)는 가장 큰 유사도를 리턴해줍니다! 
#문제는 actions를 정의해줘야해요..
