# Generated by Django 4.2.1 on 2023-05-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('alternativeTitle', models.TextField()),
                ('language', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True, verbose_name='SITE_NAME')),
                ('subDescription', models.TextField(blank=True, null=True)),
                ('referenceIdentifier', models.URLField(blank=True, null=True, verbose_name='Identifier')),
            ],
        ),
    ]
